version: "3"

services:
  redis:
    # JHtyBtMd4uvx20G8
    image: redis:3.2
    volumes:
      - ../redis/redis.conf:/etc/redis/redis.conf:ro
      - ../redis/data:/var/lib/redis
      - ../redis/logs:/var/log/redis
    command:
      - redis-server
      - /etc/redis/redis.conf
    ports:
      - 6379:6379

  php:
    build: ./php
    volumes:
      - ../php/php.ini:/etc/php.ini:ro
      - ../php/supervisord.conf:/etc/supervisord.conf:ro
      - ../php/supervisor.d:/etc/supervisor.d:ro
      - ../php/crontab:/etc/crontab:ro
      - ../php/logs:/var/log/starrynight
      - ../codes:/starrynight
    links:
      - redis
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.12
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../nginx/cert:/etc/nginx/cert:ro
      - ../nginx/logs:/var/log/nginx
      - ../codes:/starrynight
    links:
      - php
    ports:
      - 80:80
      - 443:443